apiVersion: v1
kind: ConfigMap
metadata:
  name: penwave-frontend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penwave-frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
