apiVersion: v1
kind: Service
metadata:
  name: penwave-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penwave-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: penwave-frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
