apiVersion: v1
kind: Service
metadata:
  name: penwave-frontend
  namespace: penwave
  labels:
    app.kubernetes.io/name: penwave-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: penwave-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
