{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: JWT_ACCESS_SECRET
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: JWT_REFRESH_SECRET
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: COOKIE_SECRET
    - secretKey: METRICS_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: METRICS_SECRET
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: DB_PASSWORD
    - secretKey: REDIS_AUTH_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: REDIS_AUTH_TOKEN
{{- end }}
